### ISSUE TITLE
After upgrading to 0.4.2 ring-sqa wont start with table_exists error

### ISSUE THREAD

**Issue by rinsekloek** [NLNOG/ring-sqa#21]
Hi Ytti,

After upgrading to 0.4.2 and issuing restart on all ring nodes it looks like the table check doesn't work anymore:

Oct 09 10:45:10 sentia01.ring.nlnog.net ring-sqad[20424]: undefined method `table_exists?' for Ring::SQA::Database::Ping:Class

I have done a workaround by commenting this check in core,rb:
#raise "Table 'pings' does not exist" unless Ring::SQA::Database.table_exists?

Can you make a decent fix for this ?

regards,
RInse Kloek

**Comment by ytti** [comment]
Could you verify the fix, I'm too lazy.
